version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  #mariadb-1
  mariadb1:
    image: mariadb:10.5
    container_name: mariadb1
    ports:
      - "3307:3306"
    env_file: .env
    environment:
      - MARIADB_USER=${MARIADB_USER_1}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD_1}
      - MARIADB_DATABASE=${MARIADB_DATABASE_1}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb1/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    cap_add:
      - all
    networks:
      - mariadb

  #mariadb-2
  mariadb2:
    image: mariadb:10.5
    container_name: mariadb2
    ports:
      - "3308:3306"
    env_file: .env   
    environment:
      - MARIADB_USER=${MARIADB_USER_2}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD_2}
      - MARIADB_DATABASE=${MARIADB_DATABASE_2}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb2/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    cap_add:
      - all
    networks:
      - mariadb

  db-loadbalancer:
    image: mariadb/maxscale:24.02.1
    ports:
      - "3306:3306"
      - "8989:8989"
    depends_on:
      - mariadb1
      - mariadb2
    networks:
      - mariadb

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mariadb1
      - mariadb2
      - db-loadbalancer
      - keycloak
    networks:
      - mariadb
      - backend_frontend

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - backend_frontend

networks:
  mariadb:
    driver: bridge
  backend_frontend:
    driver: bridge